version: '3.8'

services:
  web:
    build: .
    container_name: teststripe_backend
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate; python manage.py runserver 0.0.0.0:8001'
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=teststripe_db
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    env_file:
      - ./.env
    networks:
      - teststripe_network
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: teststripe_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - ./.env
    networks:
      - teststripe_network

networks:
  teststripe_network:
    driver: bridge
volumes:
  postgres_data: